// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ShrimpingInstagramClient is the client API for ShrimpingInstagram service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ShrimpingInstagramClient interface {
	Callback(ctx context.Context, in *CallbackRequest, opts ...grpc.CallOption) (ShrimpingInstagram_CallbackClient, error)
	Profile(ctx context.Context, in *InstagramProfileRequest, opts ...grpc.CallOption) (*InstagramResponse, error)
	Posts(ctx context.Context, in *InstagramPostRequest, opts ...grpc.CallOption) (*InstagramResponse, error)
	TopSearch(ctx context.Context, in *InstagramTopSearchRequest, opts ...grpc.CallOption) (*InstagramResponse, error)
}

type shrimpingInstagramClient struct {
	cc grpc.ClientConnInterface
}

func NewShrimpingInstagramClient(cc grpc.ClientConnInterface) ShrimpingInstagramClient {
	return &shrimpingInstagramClient{cc}
}

func (c *shrimpingInstagramClient) Callback(ctx context.Context, in *CallbackRequest, opts ...grpc.CallOption) (ShrimpingInstagram_CallbackClient, error) {
	stream, err := c.cc.NewStream(ctx, &ShrimpingInstagram_ServiceDesc.Streams[0], "/pb.shrimpingInstagram/Callback", opts...)
	if err != nil {
		return nil, err
	}
	x := &shrimpingInstagramCallbackClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ShrimpingInstagram_CallbackClient interface {
	Recv() (*InstagramResponse, error)
	grpc.ClientStream
}

type shrimpingInstagramCallbackClient struct {
	grpc.ClientStream
}

func (x *shrimpingInstagramCallbackClient) Recv() (*InstagramResponse, error) {
	m := new(InstagramResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *shrimpingInstagramClient) Profile(ctx context.Context, in *InstagramProfileRequest, opts ...grpc.CallOption) (*InstagramResponse, error) {
	out := new(InstagramResponse)
	err := c.cc.Invoke(ctx, "/pb.shrimpingInstagram/Profile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shrimpingInstagramClient) Posts(ctx context.Context, in *InstagramPostRequest, opts ...grpc.CallOption) (*InstagramResponse, error) {
	out := new(InstagramResponse)
	err := c.cc.Invoke(ctx, "/pb.shrimpingInstagram/Posts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shrimpingInstagramClient) TopSearch(ctx context.Context, in *InstagramTopSearchRequest, opts ...grpc.CallOption) (*InstagramResponse, error) {
	out := new(InstagramResponse)
	err := c.cc.Invoke(ctx, "/pb.shrimpingInstagram/TopSearch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShrimpingInstagramServer is the server API for ShrimpingInstagram service.
// All implementations must embed UnimplementedShrimpingInstagramServer
// for forward compatibility
type ShrimpingInstagramServer interface {
	Callback(*CallbackRequest, ShrimpingInstagram_CallbackServer) error
	Profile(context.Context, *InstagramProfileRequest) (*InstagramResponse, error)
	Posts(context.Context, *InstagramPostRequest) (*InstagramResponse, error)
	TopSearch(context.Context, *InstagramTopSearchRequest) (*InstagramResponse, error)
	mustEmbedUnimplementedShrimpingInstagramServer()
}

// UnimplementedShrimpingInstagramServer must be embedded to have forward compatible implementations.
type UnimplementedShrimpingInstagramServer struct {
}

func (UnimplementedShrimpingInstagramServer) Callback(*CallbackRequest, ShrimpingInstagram_CallbackServer) error {
	return status.Errorf(codes.Unimplemented, "method Callback not implemented")
}
func (UnimplementedShrimpingInstagramServer) Profile(context.Context, *InstagramProfileRequest) (*InstagramResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Profile not implemented")
}
func (UnimplementedShrimpingInstagramServer) Posts(context.Context, *InstagramPostRequest) (*InstagramResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Posts not implemented")
}
func (UnimplementedShrimpingInstagramServer) TopSearch(context.Context, *InstagramTopSearchRequest) (*InstagramResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TopSearch not implemented")
}
func (UnimplementedShrimpingInstagramServer) mustEmbedUnimplementedShrimpingInstagramServer() {}

// UnsafeShrimpingInstagramServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ShrimpingInstagramServer will
// result in compilation errors.
type UnsafeShrimpingInstagramServer interface {
	mustEmbedUnimplementedShrimpingInstagramServer()
}

func RegisterShrimpingInstagramServer(s grpc.ServiceRegistrar, srv ShrimpingInstagramServer) {
	s.RegisterService(&ShrimpingInstagram_ServiceDesc, srv)
}

func _ShrimpingInstagram_Callback_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CallbackRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ShrimpingInstagramServer).Callback(m, &shrimpingInstagramCallbackServer{stream})
}

type ShrimpingInstagram_CallbackServer interface {
	Send(*InstagramResponse) error
	grpc.ServerStream
}

type shrimpingInstagramCallbackServer struct {
	grpc.ServerStream
}

func (x *shrimpingInstagramCallbackServer) Send(m *InstagramResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _ShrimpingInstagram_Profile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InstagramProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShrimpingInstagramServer).Profile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.shrimpingInstagram/Profile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShrimpingInstagramServer).Profile(ctx, req.(*InstagramProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShrimpingInstagram_Posts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InstagramPostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShrimpingInstagramServer).Posts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.shrimpingInstagram/Posts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShrimpingInstagramServer).Posts(ctx, req.(*InstagramPostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShrimpingInstagram_TopSearch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InstagramTopSearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShrimpingInstagramServer).TopSearch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.shrimpingInstagram/TopSearch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShrimpingInstagramServer).TopSearch(ctx, req.(*InstagramTopSearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ShrimpingInstagram_ServiceDesc is the grpc.ServiceDesc for ShrimpingInstagram service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ShrimpingInstagram_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.shrimpingInstagram",
	HandlerType: (*ShrimpingInstagramServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Profile",
			Handler:    _ShrimpingInstagram_Profile_Handler,
		},
		{
			MethodName: "Posts",
			Handler:    _ShrimpingInstagram_Posts_Handler,
		},
		{
			MethodName: "TopSearch",
			Handler:    _ShrimpingInstagram_TopSearch_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Callback",
			Handler:       _ShrimpingInstagram_Callback_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "shritagram.proto",
}
