// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// VersioningClient is the client API for Versioning service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VersioningClient interface {
	Version(ctx context.Context, in *VersionRequest, opts ...grpc.CallOption) (*VersionResponse, error)
}

type versioningClient struct {
	cc grpc.ClientConnInterface
}

func NewVersioningClient(cc grpc.ClientConnInterface) VersioningClient {
	return &versioningClient{cc}
}

func (c *versioningClient) Version(ctx context.Context, in *VersionRequest, opts ...grpc.CallOption) (*VersionResponse, error) {
	out := new(VersionResponse)
	err := c.cc.Invoke(ctx, "/pb.versioning/Version", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VersioningServer is the server API for Versioning service.
// All implementations must embed UnimplementedVersioningServer
// for forward compatibility
type VersioningServer interface {
	Version(context.Context, *VersionRequest) (*VersionResponse, error)
	mustEmbedUnimplementedVersioningServer()
}

// UnimplementedVersioningServer must be embedded to have forward compatible implementations.
type UnimplementedVersioningServer struct {
}

func (UnimplementedVersioningServer) Version(context.Context, *VersionRequest) (*VersionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Version not implemented")
}
func (UnimplementedVersioningServer) mustEmbedUnimplementedVersioningServer() {}

// UnsafeVersioningServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VersioningServer will
// result in compilation errors.
type UnsafeVersioningServer interface {
	mustEmbedUnimplementedVersioningServer()
}

func RegisterVersioningServer(s grpc.ServiceRegistrar, srv VersioningServer) {
	s.RegisterService(&Versioning_ServiceDesc, srv)
}

func _Versioning_Version_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VersioningServer).Version(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.versioning/Version",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VersioningServer).Version(ctx, req.(*VersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Versioning_ServiceDesc is the grpc.ServiceDesc for Versioning service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Versioning_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.versioning",
	HandlerType: (*VersioningServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Version",
			Handler:    _Versioning_Version_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "version.proto",
}
