//shritagram is shrimping + instagram

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: shritagram.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InstagramObjectCompressionAlgorithm int32

const (
	InstagramObjectCompressionAlgorithm_NONE InstagramObjectCompressionAlgorithm = 0
	InstagramObjectCompressionAlgorithm_GZIP InstagramObjectCompressionAlgorithm = 1
)

// Enum value maps for InstagramObjectCompressionAlgorithm.
var (
	InstagramObjectCompressionAlgorithm_name = map[int32]string{
		0: "NONE",
		1: "GZIP",
	}
	InstagramObjectCompressionAlgorithm_value = map[string]int32{
		"NONE": 0,
		"GZIP": 1,
	}
)

func (x InstagramObjectCompressionAlgorithm) Enum() *InstagramObjectCompressionAlgorithm {
	p := new(InstagramObjectCompressionAlgorithm)
	*p = x
	return p
}

func (x InstagramObjectCompressionAlgorithm) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InstagramObjectCompressionAlgorithm) Descriptor() protoreflect.EnumDescriptor {
	return file_shritagram_proto_enumTypes[0].Descriptor()
}

func (InstagramObjectCompressionAlgorithm) Type() protoreflect.EnumType {
	return &file_shritagram_proto_enumTypes[0]
}

func (x InstagramObjectCompressionAlgorithm) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InstagramObjectCompressionAlgorithm.Descriptor instead.
func (InstagramObjectCompressionAlgorithm) EnumDescriptor() ([]byte, []int) {
	return file_shritagram_proto_rawDescGZIP(), []int{0}
}

type InstagramRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Usernames []string `protobuf:"bytes,1,rep,name=usernames,proto3" json:"usernames,omitempty"`
	// cacheControl has possible values:
	// no-cache: the request won't go through backend server's cache, it is revalidated with the actualy service (i.g. instagram)
	// max-age=604800: the request's result will be kept in cache with the duration(in s) specified
	//
	// default value is  max-age=86400
	CacheControl string `protobuf:"bytes,2,opt,name=cacheControl,proto3" json:"cacheControl,omitempty"`
}

func (x *InstagramRequest) Reset() {
	*x = InstagramRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shritagram_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InstagramRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstagramRequest) ProtoMessage() {}

func (x *InstagramRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shritagram_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstagramRequest.ProtoReflect.Descriptor instead.
func (*InstagramRequest) Descriptor() ([]byte, []int) {
	return file_shritagram_proto_rawDescGZIP(), []int{0}
}

func (x *InstagramRequest) GetUsernames() []string {
	if x != nil {
		return x.Usernames
	}
	return nil
}

func (x *InstagramRequest) GetCacheControl() string {
	if x != nil {
		return x.CacheControl
	}
	return ""
}

type InstagramResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RawObjects  []*RawInstgramObject                `protobuf:"bytes,1,rep,name=rawObjects,proto3" json:"rawObjects,omitempty"`
	Compression InstagramObjectCompressionAlgorithm `protobuf:"varint,2,opt,name=compression,proto3,enum=pb.InstagramObjectCompressionAlgorithm" json:"compression,omitempty"`
}

func (x *InstagramResponse) Reset() {
	*x = InstagramResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shritagram_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InstagramResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstagramResponse) ProtoMessage() {}

func (x *InstagramResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shritagram_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstagramResponse.ProtoReflect.Descriptor instead.
func (*InstagramResponse) Descriptor() ([]byte, []int) {
	return file_shritagram_proto_rawDescGZIP(), []int{1}
}

func (x *InstagramResponse) GetRawObjects() []*RawInstgramObject {
	if x != nil {
		return x.RawObjects
	}
	return nil
}

func (x *InstagramResponse) GetCompression() InstagramObjectCompressionAlgorithm {
	if x != nil {
		return x.Compression
	}
	return InstagramObjectCompressionAlgorithm_NONE
}

type RawInstgramObject struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username   string                     `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	RawProfile *RawInstagramProfileObject `protobuf:"bytes,11,opt,name=rawProfile,proto3,oneof" json:"rawProfile,omitempty"`
	RawPosts   []*RawInstagramPostObject  `protobuf:"bytes,12,rep,name=rawPosts,proto3" json:"rawPosts,omitempty"`
}

func (x *RawInstgramObject) Reset() {
	*x = RawInstgramObject{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shritagram_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RawInstgramObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawInstgramObject) ProtoMessage() {}

func (x *RawInstgramObject) ProtoReflect() protoreflect.Message {
	mi := &file_shritagram_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawInstgramObject.ProtoReflect.Descriptor instead.
func (*RawInstgramObject) Descriptor() ([]byte, []int) {
	return file_shritagram_proto_rawDescGZIP(), []int{2}
}

func (x *RawInstgramObject) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RawInstgramObject) GetRawProfile() *RawInstagramProfileObject {
	if x != nil {
		return x.RawProfile
	}
	return nil
}

func (x *RawInstgramObject) GetRawPosts() []*RawInstagramPostObject {
	if x != nil {
		return x.RawPosts
	}
	return nil
}

type RawInstagramProfileObject struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RawBytes []byte `protobuf:"bytes,1,opt,name=rawBytes,proto3" json:"rawBytes,omitempty"`
}

func (x *RawInstagramProfileObject) Reset() {
	*x = RawInstagramProfileObject{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shritagram_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RawInstagramProfileObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawInstagramProfileObject) ProtoMessage() {}

func (x *RawInstagramProfileObject) ProtoReflect() protoreflect.Message {
	mi := &file_shritagram_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawInstagramProfileObject.ProtoReflect.Descriptor instead.
func (*RawInstagramProfileObject) Descriptor() ([]byte, []int) {
	return file_shritagram_proto_rawDescGZIP(), []int{3}
}

func (x *RawInstagramProfileObject) GetRawBytes() []byte {
	if x != nil {
		return x.RawBytes
	}
	return nil
}

type RawInstagramPostObject struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Shortcode string `protobuf:"bytes,1,opt,name=shortcode,proto3" json:"shortcode,omitempty"`
	RawBytes  []byte `protobuf:"bytes,2,opt,name=rawBytes,proto3" json:"rawBytes,omitempty"`
}

func (x *RawInstagramPostObject) Reset() {
	*x = RawInstagramPostObject{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shritagram_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RawInstagramPostObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawInstagramPostObject) ProtoMessage() {}

func (x *RawInstagramPostObject) ProtoReflect() protoreflect.Message {
	mi := &file_shritagram_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawInstagramPostObject.ProtoReflect.Descriptor instead.
func (*RawInstagramPostObject) Descriptor() ([]byte, []int) {
	return file_shritagram_proto_rawDescGZIP(), []int{4}
}

func (x *RawInstagramPostObject) GetShortcode() string {
	if x != nil {
		return x.Shortcode
	}
	return ""
}

func (x *RawInstagramPostObject) GetRawBytes() []byte {
	if x != nil {
		return x.RawBytes
	}
	return nil
}

type InstagramTopSearchRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Keywords []string `protobuf:"bytes,1,rep,name=keywords,proto3" json:"keywords,omitempty"` // without `#`
}

func (x *InstagramTopSearchRequest) Reset() {
	*x = InstagramTopSearchRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shritagram_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InstagramTopSearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstagramTopSearchRequest) ProtoMessage() {}

func (x *InstagramTopSearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shritagram_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstagramTopSearchRequest.ProtoReflect.Descriptor instead.
func (*InstagramTopSearchRequest) Descriptor() ([]byte, []int) {
	return file_shritagram_proto_rawDescGZIP(), []int{5}
}

func (x *InstagramTopSearchRequest) GetKeywords() []string {
	if x != nil {
		return x.Keywords
	}
	return nil
}

type InstagramTopSearchResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RawObjects  []*RawInstgramTopSearchObject       `protobuf:"bytes,1,rep,name=rawObjects,proto3" json:"rawObjects,omitempty"`
	Compression InstagramObjectCompressionAlgorithm `protobuf:"varint,2,opt,name=compression,proto3,enum=pb.InstagramObjectCompressionAlgorithm" json:"compression,omitempty"`
}

func (x *InstagramTopSearchResponse) Reset() {
	*x = InstagramTopSearchResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shritagram_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InstagramTopSearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstagramTopSearchResponse) ProtoMessage() {}

func (x *InstagramTopSearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shritagram_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstagramTopSearchResponse.ProtoReflect.Descriptor instead.
func (*InstagramTopSearchResponse) Descriptor() ([]byte, []int) {
	return file_shritagram_proto_rawDescGZIP(), []int{6}
}

func (x *InstagramTopSearchResponse) GetRawObjects() []*RawInstgramTopSearchObject {
	if x != nil {
		return x.RawObjects
	}
	return nil
}

func (x *InstagramTopSearchResponse) GetCompression() InstagramObjectCompressionAlgorithm {
	if x != nil {
		return x.Compression
	}
	return InstagramObjectCompressionAlgorithm_NONE
}

type RawInstgramTopSearchObject struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Keyword  string `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`
	RawBytes []byte `protobuf:"bytes,2,opt,name=rawBytes,proto3" json:"rawBytes,omitempty"`
}

func (x *RawInstgramTopSearchObject) Reset() {
	*x = RawInstgramTopSearchObject{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shritagram_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RawInstgramTopSearchObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawInstgramTopSearchObject) ProtoMessage() {}

func (x *RawInstgramTopSearchObject) ProtoReflect() protoreflect.Message {
	mi := &file_shritagram_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawInstgramTopSearchObject.ProtoReflect.Descriptor instead.
func (*RawInstgramTopSearchObject) Descriptor() ([]byte, []int) {
	return file_shritagram_proto_rawDescGZIP(), []int{7}
}

func (x *RawInstgramTopSearchObject) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *RawInstgramTopSearchObject) GetRawBytes() []byte {
	if x != nil {
		return x.RawBytes
	}
	return nil
}

var File_shritagram_proto protoreflect.FileDescriptor

var file_shritagram_proto_rawDesc = []byte{
	0x0a, 0x10, 0x73, 0x68, 0x72, 0x69, 0x74, 0x61, 0x67, 0x72, 0x61, 0x6d, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x54, 0x0a, 0x10, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x67,
	0x72, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x75, 0x73,
	0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x75,
	0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x12, 0x22, 0x0a, 0x0c, 0x63, 0x61, 0x63, 0x68,
	0x65, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c,
	0x63, 0x61, 0x63, 0x68, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x22, 0x95, 0x01, 0x0a,
	0x11, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x67, 0x72, 0x61, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x35, 0x0a, 0x0a, 0x72, 0x61, 0x77, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x61, 0x77, 0x49,
	0x6e, 0x73, 0x74, 0x67, 0x72, 0x61, 0x6d, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x0a, 0x72,
	0x61, 0x77, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x12, 0x49, 0x0a, 0x0b, 0x63, 0x6f, 0x6d,
	0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x27,
	0x2e, 0x70, 0x62, 0x2e, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x67, 0x72, 0x61, 0x6d, 0x4f, 0x62, 0x6a,
	0x65, 0x63, 0x74, 0x43, 0x6f, 0x6d, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x41, 0x6c,
	0x67, 0x6f, 0x72, 0x69, 0x74, 0x68, 0x6d, 0x52, 0x0b, 0x63, 0x6f, 0x6d, 0x70, 0x72, 0x65, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x22, 0xba, 0x01, 0x0a, 0x11, 0x52, 0x61, 0x77, 0x49, 0x6e, 0x73, 0x74,
	0x67, 0x72, 0x61, 0x6d, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73,
	0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73,
	0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x42, 0x0a, 0x0a, 0x72, 0x61, 0x77, 0x50, 0x72, 0x6f,
	0x66, 0x69, 0x6c, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x70, 0x62, 0x2e,
	0x52, 0x61, 0x77, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x67, 0x72, 0x61, 0x6d, 0x50, 0x72, 0x6f, 0x66,
	0x69, 0x6c, 0x65, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x48, 0x00, 0x52, 0x0a, 0x72, 0x61, 0x77,
	0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x88, 0x01, 0x01, 0x12, 0x36, 0x0a, 0x08, 0x72, 0x61,
	0x77, 0x50, 0x6f, 0x73, 0x74, 0x73, 0x18, 0x0c, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x70,
	0x62, 0x2e, 0x52, 0x61, 0x77, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x67, 0x72, 0x61, 0x6d, 0x50, 0x6f,
	0x73, 0x74, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x08, 0x72, 0x61, 0x77, 0x50, 0x6f, 0x73,
	0x74, 0x73, 0x42, 0x0d, 0x0a, 0x0b, 0x5f, 0x72, 0x61, 0x77, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c,
	0x65, 0x22, 0x37, 0x0a, 0x19, 0x52, 0x61, 0x77, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x67, 0x72, 0x61,
	0x6d, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x1a,
	0x0a, 0x08, 0x72, 0x61, 0x77, 0x42, 0x79, 0x74, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x08, 0x72, 0x61, 0x77, 0x42, 0x79, 0x74, 0x65, 0x73, 0x22, 0x52, 0x0a, 0x16, 0x52, 0x61,
	0x77, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x67, 0x72, 0x61, 0x6d, 0x50, 0x6f, 0x73, 0x74, 0x4f, 0x62,
	0x6a, 0x65, 0x63, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x63, 0x6f, 0x64,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x63, 0x6f,
	0x64, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x61, 0x77, 0x42, 0x79, 0x74, 0x65, 0x73, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x72, 0x61, 0x77, 0x42, 0x79, 0x74, 0x65, 0x73, 0x22, 0x37,
	0x0a, 0x19, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x67, 0x72, 0x61, 0x6d, 0x54, 0x6f, 0x70, 0x53, 0x65,
	0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x6b,
	0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x6b,
	0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x73, 0x22, 0xa7, 0x01, 0x0a, 0x1a, 0x49, 0x6e, 0x73, 0x74,
	0x61, 0x67, 0x72, 0x61, 0x6d, 0x54, 0x6f, 0x70, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3e, 0x0a, 0x0a, 0x72, 0x61, 0x77, 0x4f, 0x62, 0x6a,
	0x65, 0x63, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x70, 0x62, 0x2e,
	0x52, 0x61, 0x77, 0x49, 0x6e, 0x73, 0x74, 0x67, 0x72, 0x61, 0x6d, 0x54, 0x6f, 0x70, 0x53, 0x65,
	0x61, 0x72, 0x63, 0x68, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x0a, 0x72, 0x61, 0x77, 0x4f,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x12, 0x49, 0x0a, 0x0b, 0x63, 0x6f, 0x6d, 0x70, 0x72, 0x65,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x27, 0x2e, 0x70, 0x62,
	0x2e, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x67, 0x72, 0x61, 0x6d, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74,
	0x43, 0x6f, 0x6d, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x41, 0x6c, 0x67, 0x6f, 0x72,
	0x69, 0x74, 0x68, 0x6d, 0x52, 0x0b, 0x63, 0x6f, 0x6d, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x22, 0x52, 0x0a, 0x1a, 0x52, 0x61, 0x77, 0x49, 0x6e, 0x73, 0x74, 0x67, 0x72, 0x61, 0x6d,
	0x54, 0x6f, 0x70, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12,
	0x18, 0x0a, 0x07, 0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x61, 0x77,
	0x42, 0x79, 0x74, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x72, 0x61, 0x77,
	0x42, 0x79, 0x74, 0x65, 0x73, 0x2a, 0x39, 0x0a, 0x23, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x67, 0x72,
	0x61, 0x6d, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x43, 0x6f, 0x6d, 0x70, 0x72, 0x65, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x41, 0x6c, 0x67, 0x6f, 0x72, 0x69, 0x74, 0x68, 0x6d, 0x12, 0x08, 0x0a, 0x04,
	0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x47, 0x5a, 0x49, 0x50, 0x10, 0x01,
	0x32, 0xd8, 0x01, 0x0a, 0x12, 0x73, 0x68, 0x72, 0x69, 0x6d, 0x70, 0x69, 0x6e, 0x67, 0x49, 0x6e,
	0x73, 0x74, 0x61, 0x67, 0x72, 0x61, 0x6d, 0x12, 0x3a, 0x0a, 0x07, 0x50, 0x72, 0x6f, 0x66, 0x69,
	0x6c, 0x65, 0x12, 0x14, 0x2e, 0x70, 0x62, 0x2e, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x67, 0x72, 0x61,
	0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x70, 0x62, 0x2e, 0x49, 0x6e,
	0x73, 0x74, 0x61, 0x67, 0x72, 0x61, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x30, 0x01, 0x12, 0x38, 0x0a, 0x05, 0x50, 0x6f, 0x73, 0x74, 0x73, 0x12, 0x14, 0x2e, 0x70,
	0x62, 0x2e, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x67, 0x72, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x15, 0x2e, 0x70, 0x62, 0x2e, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x67, 0x72, 0x61,
	0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x30, 0x01, 0x12, 0x4c, 0x0a,
	0x09, 0x54, 0x6f, 0x70, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x12, 0x1d, 0x2e, 0x70, 0x62, 0x2e,
	0x49, 0x6e, 0x73, 0x74, 0x61, 0x67, 0x72, 0x61, 0x6d, 0x54, 0x6f, 0x70, 0x53, 0x65, 0x61, 0x72,
	0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x70, 0x62, 0x2e, 0x49,
	0x6e, 0x73, 0x74, 0x61, 0x67, 0x72, 0x61, 0x6d, 0x54, 0x6f, 0x70, 0x53, 0x65, 0x61, 0x72, 0x63,
	0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x05, 0x5a, 0x03, 0x2f,
	0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_shritagram_proto_rawDescOnce sync.Once
	file_shritagram_proto_rawDescData = file_shritagram_proto_rawDesc
)

func file_shritagram_proto_rawDescGZIP() []byte {
	file_shritagram_proto_rawDescOnce.Do(func() {
		file_shritagram_proto_rawDescData = protoimpl.X.CompressGZIP(file_shritagram_proto_rawDescData)
	})
	return file_shritagram_proto_rawDescData
}

var file_shritagram_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_shritagram_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_shritagram_proto_goTypes = []interface{}{
	(InstagramObjectCompressionAlgorithm)(0), // 0: pb.InstagramObjectCompressionAlgorithm
	(*InstagramRequest)(nil),                 // 1: pb.InstagramRequest
	(*InstagramResponse)(nil),                // 2: pb.InstagramResponse
	(*RawInstgramObject)(nil),                // 3: pb.RawInstgramObject
	(*RawInstagramProfileObject)(nil),        // 4: pb.RawInstagramProfileObject
	(*RawInstagramPostObject)(nil),           // 5: pb.RawInstagramPostObject
	(*InstagramTopSearchRequest)(nil),        // 6: pb.InstagramTopSearchRequest
	(*InstagramTopSearchResponse)(nil),       // 7: pb.InstagramTopSearchResponse
	(*RawInstgramTopSearchObject)(nil),       // 8: pb.RawInstgramTopSearchObject
}
var file_shritagram_proto_depIdxs = []int32{
	3, // 0: pb.InstagramResponse.rawObjects:type_name -> pb.RawInstgramObject
	0, // 1: pb.InstagramResponse.compression:type_name -> pb.InstagramObjectCompressionAlgorithm
	4, // 2: pb.RawInstgramObject.rawProfile:type_name -> pb.RawInstagramProfileObject
	5, // 3: pb.RawInstgramObject.rawPosts:type_name -> pb.RawInstagramPostObject
	8, // 4: pb.InstagramTopSearchResponse.rawObjects:type_name -> pb.RawInstgramTopSearchObject
	0, // 5: pb.InstagramTopSearchResponse.compression:type_name -> pb.InstagramObjectCompressionAlgorithm
	1, // 6: pb.shrimpingInstagram.Profile:input_type -> pb.InstagramRequest
	1, // 7: pb.shrimpingInstagram.Posts:input_type -> pb.InstagramRequest
	6, // 8: pb.shrimpingInstagram.TopSearch:input_type -> pb.InstagramTopSearchRequest
	2, // 9: pb.shrimpingInstagram.Profile:output_type -> pb.InstagramResponse
	2, // 10: pb.shrimpingInstagram.Posts:output_type -> pb.InstagramResponse
	7, // 11: pb.shrimpingInstagram.TopSearch:output_type -> pb.InstagramTopSearchResponse
	9, // [9:12] is the sub-list for method output_type
	6, // [6:9] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_shritagram_proto_init() }
func file_shritagram_proto_init() {
	if File_shritagram_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_shritagram_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InstagramRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shritagram_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InstagramResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shritagram_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RawInstgramObject); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shritagram_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RawInstagramProfileObject); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shritagram_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RawInstagramPostObject); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shritagram_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InstagramTopSearchRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shritagram_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InstagramTopSearchResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shritagram_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RawInstgramTopSearchObject); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_shritagram_proto_msgTypes[2].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_shritagram_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shritagram_proto_goTypes,
		DependencyIndexes: file_shritagram_proto_depIdxs,
		EnumInfos:         file_shritagram_proto_enumTypes,
		MessageInfos:      file_shritagram_proto_msgTypes,
	}.Build()
	File_shritagram_proto = out.File
	file_shritagram_proto_rawDesc = nil
	file_shritagram_proto_goTypes = nil
	file_shritagram_proto_depIdxs = nil
}
