// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: shritagram.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InstagramRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Usernames []string `protobuf:"bytes,1,rep,name=usernames,proto3" json:"usernames,omitempty"`
}

func (x *InstagramRequest) Reset() {
	*x = InstagramRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shritagram_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InstagramRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstagramRequest) ProtoMessage() {}

func (x *InstagramRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shritagram_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstagramRequest.ProtoReflect.Descriptor instead.
func (*InstagramRequest) Descriptor() ([]byte, []int) {
	return file_shritagram_proto_rawDescGZIP(), []int{0}
}

func (x *InstagramRequest) GetUsernames() []string {
	if x != nil {
		return x.Usernames
	}
	return nil
}

type InstagramResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RawObjects []*RawInstgramObject `protobuf:"bytes,1,rep,name=rawObjects,proto3" json:"rawObjects,omitempty"`
}

func (x *InstagramResponse) Reset() {
	*x = InstagramResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shritagram_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InstagramResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstagramResponse) ProtoMessage() {}

func (x *InstagramResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shritagram_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstagramResponse.ProtoReflect.Descriptor instead.
func (*InstagramResponse) Descriptor() ([]byte, []int) {
	return file_shritagram_proto_rawDescGZIP(), []int{1}
}

func (x *InstagramResponse) GetRawObjects() []*RawInstgramObject {
	if x != nil {
		return x.RawObjects
	}
	return nil
}

type RawInstgramObject struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username   string                     `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	RawProfile *RawInstagramProfileObject `protobuf:"bytes,2,opt,name=rawProfile,proto3,oneof" json:"rawProfile,omitempty"`
	RawPosts   []*RawInstagramPostObject  `protobuf:"bytes,3,rep,name=rawPosts,proto3" json:"rawPosts,omitempty"`
}

func (x *RawInstgramObject) Reset() {
	*x = RawInstgramObject{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shritagram_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RawInstgramObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawInstgramObject) ProtoMessage() {}

func (x *RawInstgramObject) ProtoReflect() protoreflect.Message {
	mi := &file_shritagram_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawInstgramObject.ProtoReflect.Descriptor instead.
func (*RawInstgramObject) Descriptor() ([]byte, []int) {
	return file_shritagram_proto_rawDescGZIP(), []int{2}
}

func (x *RawInstgramObject) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RawInstgramObject) GetRawProfile() *RawInstagramProfileObject {
	if x != nil {
		return x.RawProfile
	}
	return nil
}

func (x *RawInstgramObject) GetRawPosts() []*RawInstagramPostObject {
	if x != nil {
		return x.RawPosts
	}
	return nil
}

type RawInstagramProfileObject struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RawBytes []byte `protobuf:"bytes,1,opt,name=rawBytes,proto3" json:"rawBytes,omitempty"`
}

func (x *RawInstagramProfileObject) Reset() {
	*x = RawInstagramProfileObject{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shritagram_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RawInstagramProfileObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawInstagramProfileObject) ProtoMessage() {}

func (x *RawInstagramProfileObject) ProtoReflect() protoreflect.Message {
	mi := &file_shritagram_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawInstagramProfileObject.ProtoReflect.Descriptor instead.
func (*RawInstagramProfileObject) Descriptor() ([]byte, []int) {
	return file_shritagram_proto_rawDescGZIP(), []int{3}
}

func (x *RawInstagramProfileObject) GetRawBytes() []byte {
	if x != nil {
		return x.RawBytes
	}
	return nil
}

type RawInstagramPostObject struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Shortcode string `protobuf:"bytes,1,opt,name=shortcode,proto3" json:"shortcode,omitempty"`
	RawBytes  []byte `protobuf:"bytes,2,opt,name=rawBytes,proto3" json:"rawBytes,omitempty"`
}

func (x *RawInstagramPostObject) Reset() {
	*x = RawInstagramPostObject{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shritagram_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RawInstagramPostObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawInstagramPostObject) ProtoMessage() {}

func (x *RawInstagramPostObject) ProtoReflect() protoreflect.Message {
	mi := &file_shritagram_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawInstagramPostObject.ProtoReflect.Descriptor instead.
func (*RawInstagramPostObject) Descriptor() ([]byte, []int) {
	return file_shritagram_proto_rawDescGZIP(), []int{4}
}

func (x *RawInstagramPostObject) GetShortcode() string {
	if x != nil {
		return x.Shortcode
	}
	return ""
}

func (x *RawInstagramPostObject) GetRawBytes() []byte {
	if x != nil {
		return x.RawBytes
	}
	return nil
}

var File_shritagram_proto protoreflect.FileDescriptor

var file_shritagram_proto_rawDesc = []byte{
	0x0a, 0x10, 0x73, 0x68, 0x72, 0x69, 0x74, 0x61, 0x67, 0x72, 0x61, 0x6d, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x30, 0x0a, 0x10, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x67,
	0x72, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x75, 0x73,
	0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x75,
	0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x22, 0x4a, 0x0a, 0x11, 0x49, 0x6e, 0x73, 0x74,
	0x61, 0x67, 0x72, 0x61, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x35, 0x0a,
	0x0a, 0x72, 0x61, 0x77, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x15, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x61, 0x77, 0x49, 0x6e, 0x73, 0x74, 0x67, 0x72,
	0x61, 0x6d, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x0a, 0x72, 0x61, 0x77, 0x4f, 0x62, 0x6a,
	0x65, 0x63, 0x74, 0x73, 0x22, 0xba, 0x01, 0x0a, 0x11, 0x52, 0x61, 0x77, 0x49, 0x6e, 0x73, 0x74,
	0x67, 0x72, 0x61, 0x6d, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73,
	0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73,
	0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x42, 0x0a, 0x0a, 0x72, 0x61, 0x77, 0x50, 0x72, 0x6f,
	0x66, 0x69, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x70, 0x62, 0x2e,
	0x52, 0x61, 0x77, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x67, 0x72, 0x61, 0x6d, 0x50, 0x72, 0x6f, 0x66,
	0x69, 0x6c, 0x65, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x48, 0x00, 0x52, 0x0a, 0x72, 0x61, 0x77,
	0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x88, 0x01, 0x01, 0x12, 0x36, 0x0a, 0x08, 0x72, 0x61,
	0x77, 0x50, 0x6f, 0x73, 0x74, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x70,
	0x62, 0x2e, 0x52, 0x61, 0x77, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x67, 0x72, 0x61, 0x6d, 0x50, 0x6f,
	0x73, 0x74, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x08, 0x72, 0x61, 0x77, 0x50, 0x6f, 0x73,
	0x74, 0x73, 0x42, 0x0d, 0x0a, 0x0b, 0x5f, 0x72, 0x61, 0x77, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c,
	0x65, 0x22, 0x37, 0x0a, 0x19, 0x52, 0x61, 0x77, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x67, 0x72, 0x61,
	0x6d, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x1a,
	0x0a, 0x08, 0x72, 0x61, 0x77, 0x42, 0x79, 0x74, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x08, 0x72, 0x61, 0x77, 0x42, 0x79, 0x74, 0x65, 0x73, 0x22, 0x52, 0x0a, 0x16, 0x52, 0x61,
	0x77, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x67, 0x72, 0x61, 0x6d, 0x50, 0x6f, 0x73, 0x74, 0x4f, 0x62,
	0x6a, 0x65, 0x63, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x63, 0x6f, 0x64,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x63, 0x6f,
	0x64, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x61, 0x77, 0x42, 0x79, 0x74, 0x65, 0x73, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x72, 0x61, 0x77, 0x42, 0x79, 0x74, 0x65, 0x73, 0x32, 0x8a,
	0x01, 0x0a, 0x12, 0x73, 0x68, 0x72, 0x69, 0x6d, 0x70, 0x69, 0x6e, 0x67, 0x49, 0x6e, 0x73, 0x74,
	0x61, 0x67, 0x72, 0x61, 0x6d, 0x12, 0x3a, 0x0a, 0x07, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65,
	0x12, 0x14, 0x2e, 0x70, 0x62, 0x2e, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x67, 0x72, 0x61, 0x6d, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x70, 0x62, 0x2e, 0x49, 0x6e, 0x73, 0x74,
	0x61, 0x67, 0x72, 0x61, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x30,
	0x01, 0x12, 0x38, 0x0a, 0x05, 0x50, 0x6f, 0x73, 0x74, 0x73, 0x12, 0x14, 0x2e, 0x70, 0x62, 0x2e,
	0x49, 0x6e, 0x73, 0x74, 0x61, 0x67, 0x72, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x15, 0x2e, 0x70, 0x62, 0x2e, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x67, 0x72, 0x61, 0x6d, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x30, 0x01, 0x42, 0x05, 0x5a, 0x03, 0x2f,
	0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_shritagram_proto_rawDescOnce sync.Once
	file_shritagram_proto_rawDescData = file_shritagram_proto_rawDesc
)

func file_shritagram_proto_rawDescGZIP() []byte {
	file_shritagram_proto_rawDescOnce.Do(func() {
		file_shritagram_proto_rawDescData = protoimpl.X.CompressGZIP(file_shritagram_proto_rawDescData)
	})
	return file_shritagram_proto_rawDescData
}

var file_shritagram_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_shritagram_proto_goTypes = []interface{}{
	(*InstagramRequest)(nil),          // 0: pb.InstagramRequest
	(*InstagramResponse)(nil),         // 1: pb.InstagramResponse
	(*RawInstgramObject)(nil),         // 2: pb.RawInstgramObject
	(*RawInstagramProfileObject)(nil), // 3: pb.RawInstagramProfileObject
	(*RawInstagramPostObject)(nil),    // 4: pb.RawInstagramPostObject
}
var file_shritagram_proto_depIdxs = []int32{
	2, // 0: pb.InstagramResponse.rawObjects:type_name -> pb.RawInstgramObject
	3, // 1: pb.RawInstgramObject.rawProfile:type_name -> pb.RawInstagramProfileObject
	4, // 2: pb.RawInstgramObject.rawPosts:type_name -> pb.RawInstagramPostObject
	0, // 3: pb.shrimpingInstagram.Profile:input_type -> pb.InstagramRequest
	0, // 4: pb.shrimpingInstagram.Posts:input_type -> pb.InstagramRequest
	1, // 5: pb.shrimpingInstagram.Profile:output_type -> pb.InstagramResponse
	1, // 6: pb.shrimpingInstagram.Posts:output_type -> pb.InstagramResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_shritagram_proto_init() }
func file_shritagram_proto_init() {
	if File_shritagram_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_shritagram_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InstagramRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shritagram_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InstagramResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shritagram_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RawInstgramObject); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shritagram_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RawInstagramProfileObject); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shritagram_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RawInstagramPostObject); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_shritagram_proto_msgTypes[2].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_shritagram_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shritagram_proto_goTypes,
		DependencyIndexes: file_shritagram_proto_depIdxs,
		MessageInfos:      file_shritagram_proto_msgTypes,
	}.Build()
	File_shritagram_proto = out.File
	file_shritagram_proto_rawDesc = nil
	file_shritagram_proto_goTypes = nil
	file_shritagram_proto_depIdxs = nil
}
